### ISSUE TITLE
国际化如何使用

### ISSUE THREAD

**Issue by yexiaodong** [haoziqaq/varlet#101]
有完整的国际例子吗？官网不够详细，如：1.国际化的语言文件位置、格式；2.如何在html和js中使用

**Comment by haoziqaq** [comment]
1.我们后续完善一下文档
2.您说的在html和js中使用是指在多页应用的使用场景下么?

**Comment by yexiaodong** [comment]
vue单文件中

**Comment by haoziqaq** [comment]
后续我们会优化一下这块的文档

首先挂载我们内置的英文语言包，也可以自己扩展自己的语言，具体格式可以直接去查看我们内置的英文语言包
```js
// main.js
import { Locale } from '@varlet/ui'
import enUS from '@varlet/ui/es/locale/en-US'

Locale.add('en-US', enUS)
```

然后在你想切换语言的地方切换就可以了，比如这样
```vue
<template>
  <var-button @click="change">切换成英文</var-button>
</template>

<script>
import { Locale } from '@varlet/ui'

export default {
  setup() {
    const change = () => Locale.use('en-US')

    return {
      change
    }
  }
}
</script>
```

**Comment by haoziqaq** [comment]
如果不能解决你的问题，我们邀请你进入我们的群，也方便交流。

**Comment by yexiaodong** [comment]
QQ：2283138757

**Comment by yexiaodong** [comment]
语言包已经知道怎样维护了，但是应该怎样在template模块中，使用这些语言包？你上面的例子只是切换语言。

**Comment by haoziqaq** [comment]
你是想用Locale模块去做整个应用的国际化，并非只有组件库的国际化是么？

**Comment by xxj2016** [comment]
你好，请问怎么添加组件库的国际化语言？现在组件只内置了中文跟英文，怎么添加使用其他语言哈？比如，越南语，韩语。感谢

**Comment by estoi** [comment]
> 你是想用Locale模块去做整个应用的国际化，并非只有组件库的国际化是么？

这种需要怎么实现呢

**Comment by estoi** [comment]
> > 你是想用Locale模块去做整个应用的国际化，并非只有组件库的国际化是么？
> 
> 这种需要怎么实现呢 @haoziqaq

已经用 [vue-i18n](https://github.com/intlify/vue-i18n-next)实现了
