### ISSUE TITLE
有哪些内置的图标？

### ISSUE THREAD

**Issue by yexiaodong** [haoziqaq/varlet#102]
“Material Design Icon”中的图标是否全部内置？如下代码不显示图标
`
<var-icon name="angle-acute" />
`

**Comment by haoziqaq** [comment]
Material Design Icon中的icon太多了，全部内置不太现实，只内置一些基础的图标，在文档icon组件里可以看到，如果有特别需要的icon需要内置，可以给我们packages/varlet-icons这个包pr，会在下一个版本中合并到内置icon里
