### ISSUE TITLE
有没有计划推出uni-app版的?

### ISSUE THREAD

**Issue by Ryokutouto** [haoziqaq/varlet#105]

**Comment by XeryYue** [comment]
uniapp版本的话 估计不太好弄。估计得新开仓库。因为2个的编译出来不太一样。需要兼容的点很多。具体的咱也不懂。能支持估计也是vue3 composition api的方式进行支持。 我猜测是这样的方式

**Comment by haoziqaq** [comment]
XeryYue说的其实差不多了，实际上我们也在考虑去接哪家的dsl，是uni-app还是taro还在考虑之中，个人感觉这两个dsl并没有足够灵活到让我们很容易的实现这个Varlet所有的效果，所以就是有计划，但是时间不充裕，现有的跨端方案的可靠程度我们也在调研，短时间不会启动，要做就好好做，我们也不希望做一拍脑袋的方案。

**Comment by XeryYue** [comment]
> 现这个Varlet所有的效果，所以就是有计划，但是时间不充裕，现有的跨端

如果是跨端taro是可以。但是uniapp实在是不行。绑定的东西太多了

**Comment by haoziqaq** [comment]
总之就是暂时没精力去做，先把web做稳定。还是谢谢您支持

**Comment by liudonghua123** [comment]
使用 kbone 来兼容呢？
