### ISSUE TITLE
想来打个杂，您看可以吗

### ISSUE THREAD

**Issue by ahqrt** [haoziqaq/varlet#11]
在掘金看到了您的文章，想尝试一下，1217223113@qq.com

**Comment by CJayHe** [comment]
哪篇文章，我也看下。

**Comment by ahqrt** [comment]
https://juejin.cn/post/6961701657205800967


您在掘金发的这篇文章，我刚看到，您加我qq了，我进群了现在


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "haoziqaq/varlet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月13日(星期四) 晚上11:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [haoziqaq/varlet] 想来打个杂，您看可以吗 (#11)





 
哪篇文章，我也看下。

**Comment by xiefeng66** [comment]
掘金看见您的文章, 我也想打杂，243850864@qq.com

**Comment by haoziqaq** [comment]
> 掘金看见您的文章, 我也想打杂，[243850864@qq.com](mailto:243850864@qq.com)

邮件已发

**Comment by xiefeng66** [comment]
拉我进下群呗 , 2438540864@qq.com

**Comment by haoziqaq** [comment]
> 拉我进下群呗 , [2438540864@qq.com](mailto:2438540864@qq.com) 邮件已发

**Comment by canvascat** [comment]
hope to join, canvascat@qq.com

**Comment by haoziqaq** [comment]
> hope to join, [canvascat@qq.com](mailto:canvascat@qq.com)
I have sent you an invitation email
