### ISSUE TITLE
var-input 浏览器自动填充账号密码时有bug

### ISSUE THREAD

**Issue by yexiaodong** [haoziqaq/varlet#110]
浏览器：chrome92
当浏览器记住密码后样式出现如下bug：
![image](https://user-images.githubusercontent.com/13914749/127328771-f6ed0fd1-00a9-4e16-9181-55dc42ba4aea.png)

**Comment by yuding2019** [comment]
感谢您的反馈，正在修复中

**Comment by yexiaodong** [comment]
已经升级到最新版本（V 1.11.1），但是问题还未解决。

**Comment by haoziqaq** [comment]
1.11.1中未包含此次更新，可以尝试升级1.12.0
