### ISSUE TITLE
轮播组件在PC页面中滑动切换不生效

### ISSUE THREAD

**Issue by yexiaodong** [haoziqaq/varlet#112]
swipe 轮播图在PC端无法通过鼠标滑动切换，同时能否加上prev\next切换接口

**Comment by yuding2019** [comment]
感谢反馈。你是想通过鼠标滚轮进行切换还是单纯鼠标滑动切换呢，如果后者，由于组件库是基于`touch`事件，不支持桌面端的`mouse`事件，如需适配桌面端，请尝试安装`@varlet/touch-emulator`进行适配

**Comment by yexiaodong** [comment]
好的，谢谢。我刚刚还发现一个问题：在移动端旋转屏幕，轮播图的大小不会变化。prev\next切换接口能支持吗？

**Comment by haoziqaq** [comment]
prev next现在就已经支持的 可以看下文档 方法那一栏里
轮播图大小不变化的问题我们稍后就修复

**Comment by haoziqaq** [comment]
修复了，感谢兄弟

**Comment by yexiaodong** [comment]
安装@varlet/touch-emulator，并在main.js中导入。但是切换效果不理想：
希望效果：按住鼠标左键滑动时，切换
当前效果：按住鼠标左键滑动，然后松开，再次滑动才切换
`
import '@varlet/touch-emulator'
`

**Comment by yexiaodong** [comment]
prev\next\resize方法已经可以正常使用了，谢谢
