### ISSUE TITLE
time-picker能否增加一个数组prop配置可选分钟

### ISSUE THREAD

**Issue by AAaNEIgeiDEItao** [haoziqaq/varlet#116]
:hour-options="[ 3, 6, 9 ]"
:minute-options="[0, 15, 30, 45]"

**Comment by BeADre** [comment]
你是想表盘上只有传入的数字？ 不太可能会这样支持，因为这样布局显示会很奇怪

**Comment by AAaNEIgeiDEItao** [comment]
不是无序的数字 是 比如只支持每15分钟一选

**Comment by BeADre** [comment]
你的使用场景是啥？ 如果是不希望对应的时间被选择 那么`时间限制`应该是可以满足你需求的？

**Comment by AAaNEIgeiDEItao** [comment]
> 你的使用场景是啥`时间限制`？

排班系统设置时间只支持每十五分钟，不支持精确到每分钟，所以选择时间的时候要排除一些值，我现在用change事件去强制改变vmodel的值，但是指针在触摸事件后没有正确回到vmodel的值对应的角度位置

**Comment by AAaNEIgeiDEItao** [comment]
<img width="443" alt="WeChat530192df53d3eb2b65c5fa099d064302" src="https://user-images.githubusercontent.com/29647966/129125330-8d79f7a2-eba8-4911-a272-de240c739343.png">
<img width="497" alt="WeChat22acd4c124115dac66404203e7d1b4c1" src="https://user-images.githubusercontent.com/29647966/129125340-7ee604fc-b022-4971-91c6-8c68cf1b9ea5.png">

**Comment by BeADre** [comment]
ok 我懂你意思了  后面我会加一个类似`DatePicker`组件的`allowed-dates`的属性 来对时分秒具体选择时间的限制

**Comment by AAaNEIgeiDEItao** [comment]
> DatePicker

感谢！🙏

**Comment by BeADre** [comment]
对应属性已增加，升级到最新版本即可
