### ISSUE TITLE
Collapse 折叠面板 bug

### ISSUE THREAD

**Issue by yexiaodong** [haoziqaq/varlet#117]
描述
点击“模块2”，切换第二个collapse时，其内容没有显示出来
bug效果
![image](https://user-images.githubusercontent.com/13914749/129123124-8709dcaf-5031-4608-87b1-23c5fabfce27.png)

代码
![image](https://user-images.githubusercontent.com/13914749/129123474-8429c97a-23e0-4465-ab5e-cdce27aaa3bc.png)

**Comment by BeADre** [comment]
这个推荐你用`v-if`, 因为组件内部我是获取`offsetHeight`来设置高度所以一开始`v-show`为`false` 那么高度到的就是0

**Comment by yexiaodong** [comment]
我的内容比较多，resize和v-if哪种方法的性能比较好

**Comment by haoziqaq** [comment]
个人感觉，不会有什么性能的影响，这里的dom节点还没到影响性能的数量级

**Comment by yexiaodong** [comment]
好的，谢谢
