### ISSUE TITLE
关于表单验证的功能

### ISSUE THREAD

**Issue by tianyaaz** [haoziqaq/varlet#121]
form表单只有表单验证，没有验证并提交的方法，普通的表单验证会在下图的黑框里展示错误信息，假如我在验证通过之后向后台发送一个请求，要把后台错误信息用下图的黑框展示出来要怎么赋值？
![image](https://user-images.githubusercontent.com/39445492/132231818-b65a5567-ad5e-4316-bbc0-e5dac479c982.png)

**Comment by haoziqaq** [comment]
这里推荐只去校验前台的数据格式是否合法，后端的异常状态码的错误信息使用snackbar组件提示出来
如果特别想实现你说的这个效果，你有两种方式。
1.你需要在后端校验出错时，将检测有误的字段对应的rules推入一个返回后端错误信息的validator，并且调用form的validate进行二次校验，提示出错误信息，并在nextTick之后再将二次检验推入的validator移除掉
2.后端写一个校验提交字段合法性的接口（可以和提交接口使用同一个接口通过type之类的参数使其进入service层之前提前返回），使用异步validator(支持返回promise)进行后端校验,可以配合防抖，这是体验最好的方式。

**Comment by tianyaaz** [comment]
> 这里推荐只去校验前台的数据格式是否合法，后端的异常状态码的错误信息使用snackbar组件提示出来
> 如果特别想实现你说的这个效果，你有两种方式。
> 1.你需要在后端校验出错时，将检测有误的字段对应的rules推入一个返回后端错误信息的validator，并且调用form的validate进行二次校验，提示出错误信息，并在nextTick之后再将二次检验推入的validator移除掉
> 2.后端写一个校验提交字段合法性的接口（可以和提交接口使用同一个接口通过type之类的参数使其进入service层之前提前返回），使用异步validator(支持返回promise)进行后端校验,可以配合防抖，这是体验最好的方式。

那怎么实现校验并提交呢
