### ISSUE TITLE
in button events, this should be :onClick not be @click and touch is the same question.

### ISSUE THREAD

**Issue by sundada88** [haoziqaq/varlet#190]
# About `docs`
![image](https://user-images.githubusercontent.com/31195804/141395353-eb7bd88c-1949-47d2-b9fc-c01e4b52a5ce.png)

**Comment by haoziqaq** [comment]
We define the event using onXXX.
In Vue3, the template will be compiled into such a render function

```html
<button @click="handleClick">Hello World!</div>
```

```html
<button :onClick="handleClick">Hello World!</div>
```

They have the same compilation result...

```js
import { openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"

export function render(_ctx, _cache, $props, $setup, $data, $options) {
  return (_openBlock(), _createElementBlock("button", { onClick: _ctx.handleClick }, "Hello World!", 8 /* PROPS */, ["onClick"]))
}
```

Because Vue3 optimizes the render function, So both writing methods are possible. We recommend using @ grammar which is closer to the template.

**Comment by haoziqaq** [comment]
Glad to answer your question. I wiil close this issue

**Comment by sundada88** [comment]
想来打个杂，有没有人带带啊？

**Comment by sundada88** [comment]
> 想来打个杂，有没有人带带啊？

956593305@qq.com

**Comment by haoziqaq** [comment]
邮件发给你了
