### ISSUE TITLE
vue3+tsx+vite项目启动报错[vite] Internal server error: missing ) after argument list   Plugin: vite:css   File: C:/code/mcrm/node_modules/@varlet/ui/es/button/ButtonSfc.css

### ISSUE THREAD

**Issue by guozhongjia001** [haoziqaq/varlet#196]
# Bug report 🐞

## Actual results (or Errors
![微信图片_20211116095721](https://user-images.githubusercontent.com/44691489/141881748-d098fa60-7224-48f5-9b97-9f17f4109d42.png)
)

**Comment by haoziqaq** [comment]
提供一下node版本， 操作系统，运行环境，这样可以方便我们定位问题。

**Comment by guozhongjia001** [comment]
@varlet/ui": "^1.22.10，操作系统是win10，运行环境：node版本v14.17.4 npm版本 6.14.14  vue/cli版本 4.5.15

**Comment by haoziqaq** [comment]
我没有复现这个问题，可以给我一个仓库地址，我clone下来看看原因。

**Comment by guozhongjia001** [comment]
我重新使用了vue-ts模板重新安装就没问题了，我之前是单纯安装的vite模板然后自己安装的ts这些东西，然后不知道哪里出错报错。

**Comment by haoziqaq** [comment]
可能是依赖之间有些未知的影响，不过问题解决就好，再有什么问题再联系～
