### ISSUE TITLE
Module '"@varlet/ui"' has no exported member 'List', maybe List type exported absent caused it.

### ISSUE THREAD

**Issue by linkerGitHub** [haoziqaq/varlet#201]
# Feature request 🚀

### Expected:

- when I import { List } from '@varlet/ui', the TS give me an error "Module '"@varlet/ui"' has no exported member 'List'", I think the List type not been exported caused it.

### Examples:

```js
// the TS Error: Module '"@varlet/ui"' has no exported member 'List'
import { List } from '@varlet/ui';
```

### Others:
thanks for your work, I appreciate it.

**Comment by haoziqaq** [comment]
Solved, please upgrade to the latest version，Thanks for your feedback
