### ISSUE TITLE
从webpack升级到vite版本时 ，发生错误

### ISSUE THREAD

**Issue by Lastly1999** [haoziqaq/varlet#202]
# Bug report 🐞
/@fs/D:/privateProject/fast-deisgn/node_modules/.vite/vue.js?v=8b957cb3' does not provide an export named 'createElementBlock'

## Version & Environment
Node.js Version v14.17.1 Chrome Version 96.0.4664.45
varlet-cli Version 1.23.5

**Comment by haoziqaq** [comment]
Vue3的peer依赖也变了，建议装最新版cli运行gen命令生成一个新的模板，将你已经完成的组件代码直接粘贴过来，迁移难度会比较低。

**Comment by Lastly1999** [comment]
好的，感谢
