### ISSUE TITLE
vite按需加载报错

### ISSUE THREAD

**Issue by hluxiao** [haoziqaq/varlet#229]
## 问题描述：
基于 create-vue创建的vite、ts、vue3项目模板，配置按需引入报错找不到模块“unplugin-vue-components/vite”或其相应的类型声明，无法启动

## 环境：
macOS、nodev16.13.1

## 报错截图
![image](https://user-images.githubusercontent.com/40883336/146497250-5325f444-fb41-4093-91d9-0d0552802dc3.png)

![image](https://user-images.githubusercontent.com/40883336/146497101-e4dd76d0-375e-40b8-bde8-e5055a895dcf.png)

**Comment by BeADre** [comment]
你安装这个插件了吗

**Comment by hluxiao** [comment]
安装了的， 依赖删除后重新装 好了
