### ISSUE TITLE
提个代码预览折叠需求

### ISSUE THREAD

**Issue by z851103999** [haoziqaq/varlet#230]
#### 一直用这个项目的功能组件库的功能，非常好用，可以让我专注于组件开发。我希望作者是否可以提供代码折叠功能，和复制功能。

**Comment by haoziqaq** [comment]
我们正在做折叠菜单，到时候cli会进行一次重构，你说的这些功能都会提供，我们做东西比较抠细节，可能不会紧赶慢赶的上线，所以还需要一些时间，稍微再等等啦。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月17日(周五) 晚上9:54
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [haoziqaq/varlet] 提个代码预览折叠需求 (Issue #230)




 
一直用这个项目的功能组件库的功能，非常好用，可以让我专注于组件开发。我希望作者是否可以提供代码折叠功能，和复制功能。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by haoziqaq** [comment]
@varlet/cli@1.23.12-alpha.25 加入了代码折叠和复制功能，并默认开启，可以试用一下
