### ISSUE TITLE
申请加入

### ISSUE THREAD

**Issue by linkscope** [haoziqaq/varlet#236]
我可以帮忙重构最新的setup语法，可以看一下我的[demo](https://github.com/linkscope/vue-arco-admin-template/blob/master/src/components/Icon/index.vue)

也可以完全做成像ant-design-vue那样的tsx解析模板，可以看一下我的[demo](https://github.com/linkscope/vue-music-app)

另外有兴趣的话我也可以帮忙从lerna重构为符合现代的[pnpm](https://pnpm.io/)作为monorepo

有兴趣的话可以联系我linkscope@foxmail.com

**Comment by wangKBweb** [comment]
群号发过去了，进群聊聊hxd。
