### ISSUE TITLE
申请加入

### ISSUE THREAD

**Issue by kaiyuanbear** [haoziqaq/varlet#252]
在掘金上看到项目的介绍，十分感兴趣，希望能够加入作出力所能及的贡献，感谢呀，49461753@qq.com

**Comment by DreamHight** [comment]
在前端技术微信群发现的，十分感兴趣，希望能够加入作出力所能及的贡献，感谢呀，2963960225@qq.com

**Comment by Ludidi** [comment]
在掘金上看到的，想学习一下，619255119@qq.com

**Comment by wangKBweb** [comment]
已发送 元旦快乐
