### ISSUE TITLE
About some stylelint in .tsx

### ISSUE THREAD

**Issue by xyz-fish** [haoziqaq/varlet#254]
# About `styles` 🛠️
### i find some stylelint's error in .tsx
![WechatIMG4003](https://user-images.githubusercontent.com/23699634/147802260-b7558cfb-f534-4696-aa4e-e945a05cc2bc.jpeg)

`Expected "${toSizeUnit" to be "${tosizeunit" (function-name-case)stylelint(function-name-case)`

but i can't confirm is myself reason

### Proposal

1. can use `computed` make style not in render part
2. set stylelint(function-name-case) be 'off'

### Other
- `calc(${top.value}px + ${toSizeUnit(props.offsetY)})` i think can use `toPxNum` => `${top.value + toPxNum(props.offsetY)}px` so we not need `calc` and `toSizeUnit`

**Comment by qytayh** [comment]
1. We will take this advice, but you can also contribute to the Varlet community

other：Instead of using CLAC, which shifts the computation pressure to JS, CALC uses another thread to handle as few of the tasks we expect from JS as possible
