### ISSUE TITLE
按开发步骤启动不了

### ISSUE THREAD

**Issue by qinhua** [haoziqaq/varlet#33]
Site development building █████████████████████████ building (51%) 6/8 entries 17/17 dependencies 4/7 modules 3 active 
 babel-loader › ../../../../#OpenSource/varlet/packages/varlet-cli/site/pc/main.ts

Server running at http://0.0.0.0:8081
(node:54917) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type undefined
    at Hash.update (internal/crypto/hash.js:58:11)
    at BulkUpdateDecorator.update (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/webpack/lib/util/createHash.js:51:14)
    at NormalModule.updateHash (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/webpack/lib/NormalModule.js:1129:8)
    at Compilation._createModuleHash (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/webpack/lib/Compilation.js:3085:10)
    at Compilation.createModuleHashes (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/webpack/lib/Compilation.js:3057:10)
    at hooks.optimizeChunkModules.callAsync.err (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/webpack/lib/Compilation.js:2334:11)
    at Hook.eval [as callAsync] (eval at create (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/tapable/lib/Hook.js:18:14)
    at hooks.optimizeTree.callAsync.err (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/webpack/lib/Compilation.js:2294:36)
    at eval (eval at create (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:18:1)
(node:54917) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:54917) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by BeADre** [comment]
直接在根目录下 `yarn bootstrap` 就报错了？

**Comment by haoziqaq** [comment]
> Site development building █████████████████████████ building (51%) 6/8 entries 17/17 dependencies 4/7 modules 3 active
> babel-loader › ../../../../#OpenSource/varlet/packages/varlet-cli/site/pc/main.ts
> 
> Server running at http://0.0.0.0:8081
> (node:54917) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type undefined
> at Hash.update (internal/crypto/hash.js:58:11)
> at BulkUpdateDecorator.update (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/webpack/lib/util/createHash.js:51:14)
> at NormalModule.updateHash (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/webpack/lib/NormalModule.js:1129:8)
> at Compilation._createModuleHash (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/webpack/lib/Compilation.js:3085:10)
> at Compilation.createModuleHashes (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/webpack/lib/Compilation.js:3057:10)
> at hooks.optimizeChunkModules.callAsync.err (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/webpack/lib/Compilation.js:2334:11)
> at Hook.eval [as callAsync] (eval at create (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/tapable/lib/HookCodeFactory.js:33:10), :10:1)
> at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/tapable/lib/Hook.js:18:14)
> at hooks.optimizeTree.callAsync.err (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/webpack/lib/Compilation.js:2294:36)
> at eval (eval at create (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/tapable/lib/HookCodeFactory.js:33:10), :18:1)
> (node:54917) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:54917) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

请提供一下你的node版本 或是留下你的邮箱 我邀请你进群详细交流

**Comment by qinhua** [comment]
> > Site development building █████████████████████████ building (51%) 6/8 entries 17/17 dependencies 4/7 modules 3 active
> > babel-loader › ../../../../#OpenSource/varlet/packages/varlet-cli/site/pc/main.ts
> > Server running at http://0.0.0.0:8081
> > (node:54917) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type undefined
> > at Hash.update (internal/crypto/hash.js:58:11)
> > at BulkUpdateDecorator.update (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/webpack/lib/util/createHash.js:51:14)
> > at NormalModule.updateHash (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/webpack/lib/NormalModule.js:1129:8)
> > at Compilation._createModuleHash (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/webpack/lib/Compilation.js:3085:10)
> > at Compilation.createModuleHashes (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/webpack/lib/Compilation.js:3057:10)
> > at hooks.optimizeChunkModules.callAsync.err (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/webpack/lib/Compilation.js:2334:11)
> > at Hook.eval [as callAsync] (eval at create (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/tapable/lib/HookCodeFactory.js:33:10), :10:1)
> > at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/tapable/lib/Hook.js:18:14)
> > at hooks.optimizeTree.callAsync.err (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/webpack/lib/Compilation.js:2294:36)
> > at eval (eval at create (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/tapable/lib/HookCodeFactory.js:33:10), :18:1)
> > (node:54917) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> > (node:54917) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 
> 请提供一下你的node版本 或是留下你的邮箱 我邀请你进群详细交流

node版本：14.17.0，尝试过10左右的版本也是同样的错
邮箱：352484005@qq.com

**Comment by haoziqaq** [comment]
> > > Site development building █████████████████████████ building (51%) 6/8 entries 17/17 dependencies 4/7 modules 3 active
> > > babel-loader › ../../../../#OpenSource/varlet/packages/varlet-cli/site/pc/main.ts
> > > Server running at http://0.0.0.0:8081
> > > (node:54917) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type undefined
> > > at Hash.update (internal/crypto/hash.js:58:11)
> > > at BulkUpdateDecorator.update (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/webpack/lib/util/createHash.js:51:14)
> > > at NormalModule.updateHash (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/webpack/lib/NormalModule.js:1129:8)
> > > at Compilation._createModuleHash (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/webpack/lib/Compilation.js:3085:10)
> > > at Compilation.createModuleHashes (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/webpack/lib/Compilation.js:3057:10)
> > > at hooks.optimizeChunkModules.callAsync.err (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/webpack/lib/Compilation.js:2334:11)
> > > at Hook.eval [as callAsync] (eval at create (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/tapable/lib/HookCodeFactory.js:33:10), :10:1)
> > > at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/tapable/lib/Hook.js:18:14)
> > > at hooks.optimizeTree.callAsync.err (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/webpack/lib/Compilation.js:2294:36)
> > > at eval (eval at create (/Users/qinhua/Desktop/MyCode/#OpenSource/varlet/node_modules/tapable/lib/HookCodeFactory.js:33:10), :18:1)
> > > (node:54917) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> > > (node:54917) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> > 
> > 
> > 请提供一下你的node版本 或是留下你的邮箱 我邀请你进群详细交流
> 
> node版本：14.17.0，尝试过10左右的版本也是同样的错
> 邮箱：[352484005@qq.com](mailto:352484005@qq.com)

给您邮箱发邮件了，有空查收一下。
