### ISSUE TITLE
想加入团队

### ISSUE THREAD

**Issue by ding845721213** [haoziqaq/varlet#42]
邮箱845721213@qq.com

**Comment by haoziqaq** [comment]
> 邮箱[845721213@qq.com](mailto:845721213@qq.com)

给您发了邀请邮件

**Comment by Justin12138** [comment]
邮箱 cocoj798@gmail.com

**Comment by haoziqaq** [comment]
> 邮箱 [cocoj798@gmail.com](mailto:cocoj798@gmail.com)

邀请邮件已发 请查收

**Comment by GavinHome** [comment]
yangxiaoming512@yeah.net

**Comment by haoziqaq** [comment]
> [yangxiaoming512@yeah.net](mailto:yangxiaoming512@yeah.net)

已发送 请查收

**Comment by william-xue** [comment]
我也想加入 不知道现在晚不晚？我现在从 0.13.3 开始看  1083077511@qq.com
