### ISSUE TITLE
可以给图片组件增加个放大预览功能，预览界面还能进行滑动切换

### ISSUE THREAD

**Issue by q1909568816** [haoziqaq/varlet#43]

**Comment by haoziqaq** [comment]
好的 可以考虑 暂时计划可能是单独去实现一个预览的命令式组件 我们的期望是能够支持多指旋转 手势缩放等效果 不过一些实现出来的原型被我们推翻了 在安卓手机上不够跟手 也不够流畅 总之就是体验上我们不是很满意 如果做出我们理想中体验的预览组件我们会实装到各个跟图片有关系的组件上 如果最后实现出来的效果不如我们的预期 我们就简单的给图片组件做一个放大预览的功能
再慢慢探索 总之 敬请期待吧
