### ISSUE TITLE
能不能提供侧边菜单？

### ISSUE THREAD

**Issue by gongkui** [haoziqaq/varlet#92]
能不能提供菜单组件，效果类似于 jakiestfu/Snap.js这种？
移动端如果想在菜单上和PC端有类似的导航体验，可以采用这种设计，用起来也比较像APP。

**Comment by haoziqaq** [comment]
只是考虑到用Popup组件开启左侧弹出模式就能很简单的做出类似的效果,也比较符合material design的视觉体验。我们也不确定是否有必要第一方提供这样的组件
