### ISSUE TITLE
大佬求进群学习

### ISSUE THREAD

**Issue by ijeffery3** [haoziqaq/varlet#98]
QQ：879115636

**Comment by ahqrt** [comment]
开发者群号：1035119557




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "haoziqaq/varlet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月19日(星期一) 下午2:02
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[haoziqaq/varlet] 大佬求进群学习 (#98)





 
QQ：879115636
