### ISSUE TITLE
snackbar组件同时设置:vertical="true" position="bottom"样式异常

### ISSUE THREAD

**Issue by yexiaodong** [haoziqaq/varlet#99]
`
<var-snackbar v-model:show="show" :vertical="true" position="bottom">
        这是一个消息条！！
        <template #action>
            <var-button type="primary" @click="show = !show">关闭</var-button>
        </template>
    </var-snackbar>
`
![image](https://user-images.githubusercontent.com/13914749/126250629-7ad47dbb-487c-441a-9a0a-2d2634cae4cf.png)

**Comment by haoziqaq** [comment]
好的 收到 我们尽快处理
